// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/hotstuff/hotstuff.proto

package hotstuff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VeritasNodeClient is the client API for VeritasNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VeritasNodeClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type veritasNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewVeritasNodeClient(cc grpc.ClientConnInterface) VeritasNodeClient {
	return &veritasNodeClient{cc}
}

func (c *veritasNodeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/controller.VeritasNode/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *veritasNodeClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/controller.VeritasNode/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VeritasNodeServer is the server API for VeritasNode service.
// All implementations must embed UnimplementedVeritasNodeServer
// for forward compatibility
type VeritasNodeServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	mustEmbedUnimplementedVeritasNodeServer()
}

// UnimplementedVeritasNodeServer must be embedded to have forward compatible implementations.
type UnimplementedVeritasNodeServer struct {
}

func (UnimplementedVeritasNodeServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVeritasNodeServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedVeritasNodeServer) mustEmbedUnimplementedVeritasNodeServer() {}

// UnsafeVeritasNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VeritasNodeServer will
// result in compilation errors.
type UnsafeVeritasNodeServer interface {
	mustEmbedUnimplementedVeritasNodeServer()
}

func RegisterVeritasNodeServer(s grpc.ServiceRegistrar, srv VeritasNodeServer) {
	s.RegisterService(&VeritasNode_ServiceDesc, srv)
}

func _VeritasNode_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeritasNodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.VeritasNode/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeritasNodeServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VeritasNode_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeritasNodeServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.VeritasNode/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeritasNodeServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VeritasNode_ServiceDesc is the grpc.ServiceDesc for VeritasNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VeritasNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controller.VeritasNode",
	HandlerType: (*VeritasNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _VeritasNode_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _VeritasNode_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hotstuff/hotstuff.proto",
}
